### ISSUE TITLE
Link to Github

### ISSUE THREAD

**Issue by danielepolencic** [netlify/node-client#8]
Is it possible to create a site and link it to a Github/Gitlab/Bitbucket repository automatically?

```js
client.createSite({
  name: 'my_name',
  domain: 'my_domain',
  repo: 'my_repo'
});
```

**Comment by calebeby** [comment]
I would really like to see this feature implemented in the Netlify API. It appears as though when you setup a site on netlify.com it directly (from the browser) talks to github for webhooks. @biilmann is this something that can be moved to the api, rather than being run client-side?

**Comment by calavera** [comment]
There are security benefits of doing this client side. Netlify servers don't need access to your auth token on GitHub or any other provider. You can see the implementation in https://github.com/netlify/netlify-cli if you need to do that.

I'm afraid that this is not going to change any time soon.
